#!/usr/bin/env bash
# This script displays information about subdomains of a given domain

display_info() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        output=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/ {getline; print $0}')
        record_type=$(echo "$output" | awk '{print $4}')
        destination=$(echo "$output" | awk '{print $5}')

        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

if [ "$#" -eq 1 ]; then
    display_info "$1"
elif [ "$#" -eq 2 ]; then
    display_info "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

