#!/usr/bin/env bash
# This is the HAProxy configuration file for redirecting HTTP to HTTPS

# Global settings
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

# Default SSL material locations
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

# Frontend configuration for HTTP redirection
frontend http-frontend
    bind *:80
    mode http
    option forwardfor
    option http-keep-alive
    reqadd X-Forwarded-Proto:\ http
    redirect scheme https if !{ ssl_fc }

# Frontend configuration for HTTPS
frontend https-frontend
    bind *:443 ssl crt /etc/ssl/certs/holberton.online.pem
    reqadd X-Forwarded-Proto:\ https
    acl is_ssl hdr_end(host) -i www.holberton.online
    use_backend www-backend if is_ssl

# Backend configuration
backend www-backend
    server web-01 127.0.0.1:80 check

