#!/usr/bin/env bash
# This script configures NGINX to display a custom 404 page

# Check if NGINX is installed
if ! command -v nginx &>/dev/null; then
    echo "NGINX is not installed. Please install NGINX first."
    exit 1
fi

# Create a custom 404 error page file
echo "Ceci n'est pas une page" | tee /usr/share/nginx/html/404.html

# Create a configuration file for the custom error page
echo "error_page 404 /404.html;
location = /404.html {
    root /usr/share/nginx/html;
    internal;
}" | tee /etc/nginx/sites-available/custom_404

# Create a symbolic link to enable the custom error page configuration
ln -sf /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test NGINX configuration syntax
nginx -t

# Restart NGINX to apply the changes
service nginx reload
