#!/usr/bin/env bash
# Fix Nginx to listen on port 80 for all active IPv4 IPs

apt-get update
apt-get install -y nginx
echo -e "listen 80;\n" | tee -a /etc/nginx/sites-available/default
service nginx restart
