#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process
# Finding the process ID (PID) of 4-to_infinity_and_beyond and sending SIGTERM signal using pkill

pkill -f "4-to_infinity_and_beyond"
