#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely 
#+ with a sleep of 2 seconds between each iteration
# It also responds to SIGTERM signal with "I am invincible!!!"

trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
