#!/usr/bin/env bash
# Displays the story of users from /etc/passwd using a while loop + IFS

# Read /etc/passwd line by line using a while loop
while IFS=":" read -r username _ userid group home shell _
do
    # Extract and display required information
    echo "The user $username is part of the $group gang, lives in $home and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
