#!/usr/bin/env bash
# This script displays "Best School" 10 times, and for the 9th iteration, it displays "Hi" on a new line.

# Initialize a counter
counter=1

# Using a while loop to display "Best School" 10 times
while [ $counter -le 10 ]
do
    # Using an if statement to check for the 9th iteration
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
