#!/usr/bin/env bash
# This script displays different messages based on the loop iteration number.

# Initialize a counter
counter=1

# Using a while loop to iterate from 1 to 10
while [ $counter -le 10 ]
do
    # Using if, elif, and else statements to display messages based on the iteration number
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
