#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with specific messages for certain iterations.

# Initialize a counter
counter=1

# Using a while loop to iterate from 1 to 20
while [ $counter -le 20 ]
do
    # Using a casy messages based on the iteration number
    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done
